import type { FashionHeroSlide } from './types';

export const fashionHeroSlides: FashionHeroSlide[] = [
  {
    id: 'new-collection',
    eyebrow: 'New Collection',
    titleLines: ['Define', 'Your', 'Presence'],
    season: 'Autumn / Winter 2026',
    description: 'Rich textures and warm, earthen hues for the season ahead — pieces built to move with you.',
    ctaLabel: 'Discover Collection',
    ctaHref: '/search?sort=newest',
    mainImage: {
      src: '/images/carousel/carousel4.jpg',
      alt: 'Model reclined among autumn leaves wearing a rust turtleneck and black dress from the new Autumn/Winter collection',
      position: '38% 35%',
    },
    backgroundColor: '#1a120b',
    foregroundColor: '#f6ede1',
    mutedColor: '#c9b8a6',
    accentColor: '#b3552e',
    theme: 'dark',
  },
  {
    id: 'evening-edit',
    eyebrow: 'Evening Edit',
    titleLines: ['After', 'Dark'],
    season: 'Limited Evening Selection',
    description: 'Sculpted silhouettes and quiet drama for nights that call for something more.',
    ctaLabel: 'Discover the Edit',
    ctaHref: '/search?sort=newest',
    mainImage: {
      src: '/images/carousel/carousel2.jpg',
      alt: 'Model in a black zip-detail top standing in a dramatically lit, moody interior',
      position: '68% 30%',
    },
    backgroundColor: '#0a0f0f',
    foregroundColor: '#eef4f2',
    mutedColor: '#a9c2bd',
    accentColor: '#4fd1c5',
    theme: 'dark',
  },
  {
    id: 'essential-pieces',
    eyebrow: 'Modern Essentials',
    titleLines: ['Quiet', 'Confidence'],
    season: 'Everyday Tailoring',
    description: 'Considered fabrics and honest construction — the pieces that anchor every wardrobe.',
    ctaLabel: 'Shop Essentials',
    ctaHref: '/search',
    mainImage: {
      src: '/images/carousel/carousel1.jpg',
      alt: 'Close-up flat lay of a grey wool overshirt with rust leather trim details',
      position: '50% 42%',
    },
    backgroundColor: '#16181a',
    foregroundColor: '#f2f1ee',
    mutedColor: '#b9b6b0',
    accentColor: '#c17a4f',
    theme: 'dark',
  },
  {
    id: 'accessories',
    eyebrow: 'Accessories',
    titleLines: ['The Final', 'Detail'],
    season: 'Bags, Shoes and Jewellery',
    description: 'The finishing pieces that complete a look — considered down to the last detail.',
    ctaLabel: 'View Accessories',
    ctaHref: '/search',
    mainImage: {
      src: '/images/carousel/carousel3.jpg',
      alt: 'Model in an oversized cream linen shirt and sunglasses against a minimal geometric white wall',
      position: '40% 20%',
    },
    backgroundColor: '#f5f4f0',
    foregroundColor: '#17181a',
    mutedColor: '#8a8378',
    accentColor: '#8a8378',
    theme: 'light',
  },
];
