// Placeholder used for all new category seed products.
// Replace each entry's images array with real product images later.
const PH = '/images/placeholder.jpg';

const sampleData = {
  users: [
    {
      name: 'John Doe',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane Doe',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    // ─────────────────────────────────────────
    // MEN'S CLOTHING
    // ─────────────────────────────────────────

    // Men's Dress Shirts (original products kept)
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },

    // Men's Sweatshirts & Hoodies (original kept)
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts & Hoodies",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Champion Reverse Weave Hoodie',
      slug: 'champion-reverse-weave-hoodie',
      category: "Men's Sweatshirts & Hoodies",
      description: 'Heavyweight fleece with a relaxed fit',
      images: [PH],
      price: 65.0,
      brand: 'Champion',
      rating: 4.4,
      numReviews: 22,
      stock: 14,
      isFeatured: false,
      banner: null,
    },

    // Men's T-Shirts & Polos
    {
      name: 'Lacoste Classic Piqué Polo',
      slug: 'lacoste-classic-pique-polo',
      category: "Men's T-Shirts & Polos",
      description: 'Iconic crocodile logo polo in premium cotton piqué',
      images: [PH],
      price: 98.0,
      brand: 'Lacoste',
      rating: 4.7,
      numReviews: 34,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Hanes Essentials Crew-Neck Tee',
      slug: 'hanes-essentials-crew-neck-tee',
      category: "Men's T-Shirts & Polos",
      description: 'Everyday comfort in ultra-soft cotton',
      images: [PH],
      price: 14.99,
      brand: 'Hanes',
      rating: 4.2,
      numReviews: 56,
      stock: 50,
      isFeatured: false,
      banner: null,
    },

    // Men's Jeans
    {
      name: "Levi's 501 Original Fit Jeans",
      slug: 'levis-501-original-fit-jeans',
      category: "Men's Jeans",
      description: 'The original straight-fit jeans since 1873',
      images: [PH],
      price: 69.5,
      brand: "Levi's",
      rating: 4.6,
      numReviews: 89,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Wrangler Authentics Classic 5-Pocket Jean',
      slug: 'wrangler-authentics-classic-5-pocket-jean',
      category: "Men's Jeans",
      description: 'Durable denim built for everyday wear',
      images: [PH],
      price: 39.99,
      brand: 'Wrangler',
      rating: 4.1,
      numReviews: 41,
      stock: 25,
      isFeatured: false,
      banner: null,
    },

    // Men's Pants & Chinos
    {
      name: 'Dockers Alpha Slim Tapered Khaki',
      slug: 'dockers-alpha-slim-tapered-khaki',
      category: "Men's Pants & Chinos",
      description: 'Smart casual khakis with a modern tapered silhouette',
      images: [PH],
      price: 54.99,
      brand: 'Dockers',
      rating: 4.3,
      numReviews: 27,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Gap Straight Fit Khaki Chinos',
      slug: 'gap-straight-fit-khaki-chinos',
      category: "Men's Pants & Chinos",
      description: 'Versatile chinos that go from office to weekend',
      images: [PH],
      price: 49.95,
      brand: 'Gap',
      rating: 4.0,
      numReviews: 19,
      stock: 22,
      isFeatured: false,
      banner: null,
    },

    // Men's Shorts
    {
      name: 'Nike Dri-FIT 7" Training Shorts',
      slug: 'nike-dri-fit-7-training-shorts',
      category: "Men's Shorts",
      description: 'Lightweight and breathable for intense workouts',
      images: [PH],
      price: 35.0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 44,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Quiksilver Waterman Cargo Walk Shorts',
      slug: 'quiksilver-waterman-cargo-walk-shorts',
      category: "Men's Shorts",
      description: 'Casual shorts with a relaxed fit and utility pockets',
      images: [PH],
      price: 44.95,
      brand: 'Quiksilver',
      rating: 4.2,
      numReviews: 16,
      stock: 12,
      isFeatured: false,
      banner: null,
    },

    // Men's Suits & Blazers
    {
      name: 'Hugo Boss Slim Fit Wool Suit',
      slug: 'hugo-boss-slim-fit-wool-suit',
      category: "Men's Suits & Blazers",
      description: 'Premium Italian wool suit with a sharp slim cut',
      images: [PH],
      price: 549.0,
      brand: 'Hugo Boss',
      rating: 4.8,
      numReviews: 11,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Armani Exchange Single-Breasted Blazer',
      slug: 'armani-exchange-single-breasted-blazer',
      category: "Men's Suits & Blazers",
      description: 'Sleek structured blazer for smart-casual occasions',
      images: [PH],
      price: 179.0,
      brand: 'Armani Exchange',
      rating: 4.5,
      numReviews: 9,
      stock: 8,
      isFeatured: false,
      banner: null,
    },

    // Men's Jackets & Coats
    {
      name: 'The North Face McMurdo Parka',
      slug: 'north-face-mcmurdo-parka',
      category: "Men's Jackets & Coats",
      description: '700-fill goose down insulation for extreme cold',
      images: [PH],
      price: 299.0,
      brand: 'The North Face',
      rating: 4.7,
      numReviews: 63,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Levi's Trucker Denim Jacket",
      slug: 'levis-trucker-denim-jacket',
      category: "Men's Jackets & Coats",
      description: 'The original trucker in classic rigid denim',
      images: [PH],
      price: 89.5,
      brand: "Levi's",
      rating: 4.4,
      numReviews: 38,
      stock: 16,
      isFeatured: false,
      banner: null,
    },

    // Men's Activewear
    {
      name: 'Adidas Techfit Compression Tee',
      slug: 'adidas-techfit-compression-tee',
      category: "Men's Activewear",
      description: 'Muscle-mapping compression for peak performance',
      images: [PH],
      price: 45.0,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 29,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Under Armour Rival Terry Jogger',
      slug: 'under-armour-rival-terry-jogger',
      category: "Men's Activewear",
      description: 'Soft terry fleece with a tapered athletic fit',
      images: [PH],
      price: 55.0,
      brand: 'Under Armour',
      rating: 4.3,
      numReviews: 21,
      stock: 28,
      isFeatured: false,
      banner: null,
    },

    // Men's Underwear & Socks
    {
      name: 'Calvin Klein 3-Pack Cotton Boxer Briefs',
      slug: 'calvin-klein-3-pack-cotton-boxer-briefs',
      category: "Men's Underwear & Socks",
      description: 'Classic waistband comfort in breathable cotton',
      images: [PH],
      price: 34.99,
      brand: 'Calvin Klein',
      rating: 4.6,
      numReviews: 72,
      stock: 60,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Stance Icon Athletic Crew Socks',
      slug: 'stance-icon-athletic-crew-socks',
      category: "Men's Underwear & Socks",
      description: 'Arch support and moisture management in every step',
      images: [PH],
      price: 18.0,
      brand: 'Stance',
      rating: 4.4,
      numReviews: 48,
      stock: 80,
      isFeatured: false,
      banner: null,
    },

    // Men's Swimwear
    {
      name: 'Speedo Endurance+ Jammer Swimsuit',
      slug: 'speedo-endurance-jammer-swimsuit',
      category: "Men's Swimwear",
      description: 'Chlorine-resistant fabric built for serious swimmers',
      images: [PH],
      price: 49.0,
      brand: 'Speedo',
      rating: 4.5,
      numReviews: 17,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Quiksilver New Wave 18" Boardshorts',
      slug: 'quiksilver-new-wave-18-boardshorts',
      category: "Men's Swimwear",
      description: 'Quick-dry boardshorts with a four-way stretch',
      images: [PH],
      price: 54.95,
      brand: 'Quiksilver',
      rating: 4.3,
      numReviews: 23,
      stock: 18,
      isFeatured: false,
      banner: null,
    },

    // Men's Sweaters & Knitwear
    {
      name: 'Ralph Lauren Cable-Knit Cotton Sweater',
      slug: 'ralph-lauren-cable-knit-cotton-sweater',
      category: "Men's Sweaters & Knitwear",
      description: 'Heritage cable-knit in 100% combed cotton',
      images: [PH],
      price: 125.0,
      brand: 'Ralph Lauren',
      rating: 4.6,
      numReviews: 31,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Uniqlo Extra Fine Merino Crewneck Sweater',
      slug: 'uniqlo-extra-fine-merino-crewneck-sweater',
      category: "Men's Sweaters & Knitwear",
      description: 'Ultra-soft merino wool that resists pilling',
      images: [PH],
      price: 59.9,
      brand: 'Uniqlo',
      rating: 4.5,
      numReviews: 55,
      stock: 20,
      isFeatured: false,
      banner: null,
    },

    // ─────────────────────────────────────────
    // WOMEN'S CLOTHING
    // ─────────────────────────────────────────

    // Women's Dresses
    {
      name: 'Zara Floral Midi Wrap Dress',
      slug: 'zara-floral-midi-wrap-dress',
      category: "Women's Dresses",
      description: 'Elegant wrap silhouette in a vibrant floral print',
      images: [PH],
      price: 69.9,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 43,
      stock: 18,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'H&M Conscious Linen Shirt Dress',
      slug: 'hm-conscious-linen-shirt-dress',
      category: "Women's Dresses",
      description: 'Breathable linen blend with a relaxed fit',
      images: [PH],
      price: 49.99,
      brand: 'H&M',
      rating: 4.2,
      numReviews: 26,
      stock: 22,
      isFeatured: false,
      banner: null,
    },

    // Women's Tops & Blouses
    {
      name: 'Vince Silk Relaxed Blouse',
      slug: 'vince-silk-relaxed-blouse',
      category: "Women's Tops & Blouses",
      description: '100% silk charmeuse with a fluid, modern drape',
      images: [PH],
      price: 195.0,
      brand: 'Vince',
      rating: 4.7,
      numReviews: 14,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Madewell Whisper Cotton Crewneck Tee',
      slug: 'madewell-whisper-cotton-crewneck-tee',
      category: "Women's Tops & Blouses",
      description: 'Featherweight cotton tee with a lived-in feel',
      images: [PH],
      price: 29.5,
      brand: 'Madewell',
      rating: 4.4,
      numReviews: 67,
      stock: 45,
      isFeatured: false,
      banner: null,
    },

    // Women's Jeans
    {
      name: "Levi's 721 High Rise Skinny Jeans",
      slug: 'levis-721-high-rise-skinny-jeans',
      category: "Women's Jeans",
      description: 'High-waisted skinny jeans that define every curve',
      images: [PH],
      price: 69.5,
      brand: "Levi's",
      rating: 4.6,
      numReviews: 98,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'AG Farrah High-Rise Bootcut Jeans',
      slug: 'ag-farrah-high-rise-bootcut-jeans',
      category: "Women's Jeans",
      description: 'A modern take on the classic bootcut silhouette',
      images: [PH],
      price: 188.0,
      brand: 'AG Jeans',
      rating: 4.5,
      numReviews: 22,
      stock: 10,
      isFeatured: false,
      banner: null,
    },

    // Women's Pants & Leggings
    {
      name: 'Lululemon Align High-Rise Pant',
      slug: 'lululemon-align-high-rise-pant',
      category: "Women's Pants & Leggings",
      description: 'Buttery-soft nulu fabric for studio and street',
      images: [PH],
      price: 98.0,
      brand: 'Lululemon',
      rating: 4.9,
      numReviews: 142,
      stock: 30,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Banana Republic Sloan Slim Ankle Pant',
      slug: 'banana-republic-sloan-slim-ankle-pant',
      category: "Women's Pants & Leggings",
      description: 'Polished slim trousers with a refined ankle length',
      images: [PH],
      price: 89.99,
      brand: 'Banana Republic',
      rating: 4.3,
      numReviews: 28,
      stock: 15,
      isFeatured: false,
      banner: null,
    },

    // Women's Skirts
    {
      name: 'A.P.C. Madras Straight Mini Skirt',
      slug: 'apc-madras-straight-mini-skirt',
      category: "Women's Skirts",
      description: 'Structured denim mini with a straight silhouette',
      images: [PH],
      price: 150.0,
      brand: 'A.P.C.',
      rating: 4.4,
      numReviews: 13,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Zara Pleated Midi Skirt',
      slug: 'zara-pleated-midi-skirt',
      category: "Women's Skirts",
      description: 'Flowing pleats in a versatile midi length',
      images: [PH],
      price: 45.9,
      brand: 'Zara',
      rating: 4.2,
      numReviews: 31,
      stock: 20,
      isFeatured: false,
      banner: null,
    },

    // Women's Sweatshirts & Hoodies
    {
      name: 'Nike Sportswear Phoenix Fleece Oversized Hoodie',
      slug: 'nike-phoenix-fleece-oversized-hoodie',
      category: "Women's Sweatshirts & Hoodies",
      description: 'Cozy oversized hoodie with signature fleece fabric',
      images: [PH],
      price: 70.0,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 54,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Free People Movement Sunny Sweatshirt',
      slug: 'free-people-sunny-sweatshirt',
      category: "Women's Sweatshirts & Hoodies",
      description: 'Vintage-inspired drop-shoulder fleece',
      images: [PH],
      price: 88.0,
      brand: 'Free People',
      rating: 4.4,
      numReviews: 19,
      stock: 12,
      isFeatured: false,
      banner: null,
    },

    // Women's Blazers & Jackets
    {
      name: 'Theory Tailor Jacket in Good Linen',
      slug: 'theory-tailor-jacket-good-linen',
      category: "Women's Blazers & Jackets",
      description: 'Refined single-button linen blazer for warm days',
      images: [PH],
      price: 365.0,
      brand: 'Theory',
      rating: 4.7,
      numReviews: 8,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Zara Oversized Double-Breasted Blazer',
      slug: 'zara-oversized-double-breasted-blazer',
      category: "Women's Blazers & Jackets",
      description: 'On-trend oversized cut with a power-dressing feel',
      images: [PH],
      price: 89.9,
      brand: 'Zara',
      rating: 4.3,
      numReviews: 37,
      stock: 14,
      isFeatured: false,
      banner: null,
    },

    // Women's Coats
    {
      name: "Max Mara Manuela Camel Hair Coat",
      slug: 'max-mara-manuela-camel-hair-coat',
      category: "Women's Coats",
      description: 'The iconic Italian camel coat — a wardrobe essential',
      images: [PH],
      price: 1890.0,
      brand: 'Max Mara',
      rating: 4.9,
      numReviews: 7,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Zara Wool-Blend Oversized Coat',
      slug: 'zara-wool-blend-oversized-coat',
      category: "Women's Coats",
      description: 'Classic long coat in a relaxed oversized silhouette',
      images: [PH],
      price: 129.0,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 42,
      stock: 11,
      isFeatured: false,
      banner: null,
    },

    // Women's Activewear
    {
      name: 'Gymshark Flex High-Waisted Shorts',
      slug: 'gymshark-flex-high-waisted-shorts',
      category: "Women's Activewear",
      description: 'Four-way stretch fabric for unrestricted movement',
      images: [PH],
      price: 45.0,
      brand: 'Gymshark',
      rating: 4.6,
      numReviews: 78,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Adidas Ultimate365 Printed Polo',
      slug: 'adidas-ultimate365-printed-polo',
      category: "Women's Activewear",
      description: 'Moisture-wicking performance polo for the golf course',
      images: [PH],
      price: 55.0,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 21,
      stock: 18,
      isFeatured: false,
      banner: null,
    },

    // Women's Lingerie & Sleepwear
    {
      name: "Victoria's Secret Satin Lace Chemise",
      slug: 'victorias-secret-satin-lace-chemise',
      category: "Women's Lingerie & Sleepwear",
      description: 'Delicate satin with floral lace trim for elegant nights',
      images: [PH],
      price: 49.95,
      brand: "Victoria's Secret",
      rating: 4.4,
      numReviews: 33,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Eberjey Gisele Modal Pajama Set',
      slug: 'eberjey-gisele-modal-pajama-set',
      category: "Women's Lingerie & Sleepwear",
      description: 'Featherlight modal for the softest night sleep',
      images: [PH],
      price: 115.0,
      brand: 'Eberjey',
      rating: 4.8,
      numReviews: 27,
      stock: 12,
      isFeatured: false,
      banner: null,
    },

    // Women's Swimwear
    {
      name: 'Summersalt The Sidestroke One-Piece',
      slug: 'summersalt-sidestroke-one-piece',
      category: "Women's Swimwear",
      description: 'Sculpting one-piece with ruching and UPF 50+',
      images: [PH],
      price: 95.0,
      brand: 'Summersalt',
      rating: 4.7,
      numReviews: 49,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Vix Paula Hermanny Triangle Bikini Top',
      slug: 'vix-paula-hermanny-triangle-bikini-top',
      category: "Women's Swimwear",
      description: 'Brazilian-cut triangle top with adjustable ties',
      images: [PH],
      price: 79.0,
      brand: 'Vix',
      rating: 4.4,
      numReviews: 18,
      stock: 10,
      isFeatured: false,
      banner: null,
    },

    // Women's Sweaters & Knitwear
    {
      name: 'J.Crew Relaxed Cashmere V-Neck Sweater',
      slug: 'jcrew-relaxed-cashmere-vneck-sweater',
      category: "Women's Sweaters & Knitwear",
      description: 'Grade-A Mongolian cashmere in a modern relaxed fit',
      images: [PH],
      price: 148.0,
      brand: 'J.Crew',
      rating: 4.8,
      numReviews: 36,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Mango Oversized Braided Knit Cardigan',
      slug: 'mango-oversized-braided-knit-cardigan',
      category: "Women's Sweaters & Knitwear",
      description: 'Cozy braided-stitch cardigan in a warm oversized drape',
      images: [PH],
      price: 79.99,
      brand: 'Mango',
      rating: 4.3,
      numReviews: 29,
      stock: 17,
      isFeatured: false,
      banner: null,
    },

    // ─────────────────────────────────────────
    // KIDS' CLOTHING
    // ─────────────────────────────────────────

    // Boys' Clothing
    {
      name: "Carter's Boys' 2-Pack Graphic Tees",
      slug: 'carters-boys-2-pack-graphic-tees',
      category: "Boys' Clothing",
      description: 'Fun prints in super-soft cotton, made to move in',
      images: [PH],
      price: 22.0,
      brand: "Carter's",
      rating: 4.5,
      numReviews: 38,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Gap Kids Boys' Pull-On Jogger",
      slug: 'gap-kids-boys-pull-on-jogger',
      category: "Boys' Clothing",
      description: 'Stretch waistband joggers perfect for active days',
      images: [PH],
      price: 29.95,
      brand: 'Gap Kids',
      rating: 4.3,
      numReviews: 24,
      stock: 35,
      isFeatured: false,
      banner: null,
    },

    // Girls' Clothing
    {
      name: "Zara Girls' Embroidered Tulle Dress",
      slug: 'zara-girls-embroidered-tulle-dress',
      category: "Girls' Clothing",
      description: 'Dreamy tulle layers with floral embroidery detailing',
      images: [PH],
      price: 39.9,
      brand: 'Zara',
      rating: 4.6,
      numReviews: 19,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    {
      name: "H&M Girls' Printed Jersey Leggings",
      slug: 'hm-girls-printed-jersey-leggings',
      category: "Girls' Clothing",
      description: 'Soft stretch leggings in fun all-over prints',
      images: [PH],
      price: 12.99,
      brand: 'H&M',
      rating: 4.2,
      numReviews: 31,
      stock: 60,
      isFeatured: false,
      banner: null,
    },

    // Baby & Toddler Clothing
    {
      name: "Carter's Baby 3-Pack Footed Pajamas",
      slug: 'carters-baby-3-pack-footed-pajamas',
      category: 'Baby & Toddler Clothing',
      description: 'Snug-fit cotton PJs in adorable prints — set of 3',
      images: [PH],
      price: 28.0,
      brand: "Carter's",
      rating: 4.8,
      numReviews: 62,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Burt's Bees Baby Organic Romper",
      slug: 'burts-bees-baby-organic-romper',
      category: 'Baby & Toddler Clothing',
      description: '100% organic cotton one-piece, gentle on baby skin',
      images: [PH],
      price: 19.95,
      brand: "Burt's Bees Baby",
      rating: 4.7,
      numReviews: 44,
      stock: 30,
      isFeatured: false,
      banner: null,
    },

    // Kids' Activewear
    {
      name: "Nike Kids' Dri-FIT Training Set",
      slug: 'nike-kids-dri-fit-training-set',
      category: "Kids' Activewear",
      description: 'Moisture-wicking top and shorts set for young athletes',
      images: [PH],
      price: 45.0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 27,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Adidas Kids' Tiro Track Pants",
      slug: 'adidas-kids-tiro-track-pants',
      category: "Kids' Activewear",
      description: 'Lightweight tapered track pants for training and play',
      images: [PH],
      price: 35.0,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 19,
      stock: 32,
      isFeatured: false,
      banner: null,
    },

    // Kids' Sleepwear & Underwear
    {
      name: "Hanna Andersson Kids' Organic PJ Set",
      slug: 'hanna-andersson-kids-organic-pj-set',
      category: "Kids' Sleepwear & Underwear",
      description: 'GOTS-certified organic cotton in playful prints',
      images: [PH],
      price: 36.0,
      brand: 'Hanna Andersson',
      rating: 4.7,
      numReviews: 33,
      stock: 28,
      isFeatured: false,
      banner: null,
    },

    // ─────────────────────────────────────────
    // ACCESSORIES
    // ─────────────────────────────────────────

    // Bags & Handbags
    {
      name: 'Coach Tabby Shoulder Bag 26',
      slug: 'coach-tabby-shoulder-bag-26',
      category: 'Bags & Handbags',
      description: 'Refined pebble leather with a modern flap closure',
      images: [PH],
      price: 395.0,
      brand: 'Coach',
      rating: 4.7,
      numReviews: 52,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Kate Spade New York Sam Icon Small Crossbody',
      slug: 'kate-spade-sam-icon-small-crossbody',
      category: 'Bags & Handbags',
      description: 'Iconic box bag in smooth saffiano leather',
      images: [PH],
      price: 248.0,
      brand: 'Kate Spade',
      rating: 4.5,
      numReviews: 31,
      stock: 11,
      isFeatured: false,
      banner: null,
    },

    // Belts
    {
      name: 'Hermès H Reversible Belt 32mm',
      slug: 'hermes-h-reversible-belt-32mm',
      category: 'Belts',
      description: 'Reversible calfskin belt with iconic H palladium buckle',
      images: [PH],
      price: 725.0,
      brand: 'Hermès',
      rating: 4.9,
      numReviews: 6,
      stock: 3,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Levi's Men's Casual Jeans Belt",
      slug: 'levis-mens-casual-jeans-belt',
      category: 'Belts',
      description: 'Full-grain leather with a classic burnished buckle',
      images: [PH],
      price: 28.0,
      brand: "Levi's",
      rating: 4.3,
      numReviews: 45,
      stock: 50,
      isFeatured: false,
      banner: null,
    },

    // Hats & Caps
    {
      name: 'New Era 59FIFTY Fitted Cap',
      slug: 'new-era-59fifty-fitted-cap',
      category: 'Hats & Caps',
      description: 'The original fitted cap — a streetwear staple',
      images: [PH],
      price: 38.0,
      brand: 'New Era',
      rating: 4.6,
      numReviews: 83,
      stock: 45,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Barbour Wax Cotton Flat Cap',
      slug: 'barbour-wax-cotton-flat-cap',
      category: 'Hats & Caps',
      description: 'Classic British flat cap in weatherproof waxed cotton',
      images: [PH],
      price: 55.0,
      brand: 'Barbour',
      rating: 4.5,
      numReviews: 18,
      stock: 12,
      isFeatured: false,
      banner: null,
    },

    // Scarves & Gloves
    {
      name: 'Acne Studios Canada New Fringe Scarf',
      slug: 'acne-studios-canada-new-fringe-scarf',
      category: 'Scarves & Gloves',
      description: 'Oversized fringed scarf in a cozy wool blend',
      images: [PH],
      price: 180.0,
      brand: 'Acne Studios',
      rating: 4.6,
      numReviews: 14,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Isotoner SmarTouch Leather Gloves',
      slug: 'isotoner-smartouch-leather-gloves',
      category: 'Scarves & Gloves',
      description: 'Genuine leather gloves with touchscreen-compatible fingertips',
      images: [PH],
      price: 39.0,
      brand: 'Isotoner',
      rating: 4.3,
      numReviews: 29,
      stock: 24,
      isFeatured: false,
      banner: null,
    },

    // Sunglasses
    {
      name: 'Ray-Ban Original Wayfarer Classic',
      slug: 'ray-ban-original-wayfarer-classic',
      category: 'Sunglasses',
      description: 'The world\'s best-selling sunglass frame, since 1952',
      images: [PH],
      price: 161.0,
      brand: 'Ray-Ban',
      rating: 4.8,
      numReviews: 117,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Oakley Holbrook Prizm Lens Sunglasses',
      slug: 'oakley-holbrook-prizm-lens-sunglasses',
      category: 'Sunglasses',
      description: 'Prizm lens technology for unmatched color contrast',
      images: [PH],
      price: 183.0,
      brand: 'Oakley',
      rating: 4.7,
      numReviews: 64,
      stock: 20,
      isFeatured: false,
      banner: null,
    },

    // Jewelry
    {
      name: 'Pandora Moments Heart Clasp Snake Chain Bracelet',
      slug: 'pandora-moments-heart-clasp-snake-chain-bracelet',
      category: 'Jewelry',
      description: 'Sterling silver snake chain with a heart-shaped clasp',
      images: [PH],
      price: 65.0,
      brand: 'Pandora',
      rating: 4.7,
      numReviews: 88,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Mejuri Gold Vermeil Dôme Ring',
      slug: 'mejuri-gold-vermeil-dome-ring',
      category: 'Jewelry',
      description: '18k gold vermeil dome ring — minimal, stacks perfectly',
      images: [PH],
      price: 75.0,
      brand: 'Mejuri',
      rating: 4.5,
      numReviews: 41,
      stock: 18,
      isFeatured: false,
      banner: null,
    },

    // Watches
    {
      name: 'Fossil Gen 6 Smartwatch 44mm',
      slug: 'fossil-gen-6-smartwatch-44mm',
      category: 'Watches',
      description: 'Wear OS smartwatch with health-tracking and fast charging',
      images: [PH],
      price: 249.0,
      brand: 'Fossil',
      rating: 4.3,
      numReviews: 55,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Seiko Presage Cocktail Time Automatic',
      slug: 'seiko-presage-cocktail-time-automatic',
      category: 'Watches',
      description: 'Japanese craftsmanship meets cocktail-inspired dial art',
      images: [PH],
      price: 425.0,
      brand: 'Seiko',
      rating: 4.8,
      numReviews: 29,
      stock: 7,
      isFeatured: false,
      banner: null,
    },

    // Ties & Pocket Squares
    {
      name: 'Ermenegildo Zegna Silk Repp Tie',
      slug: 'ermenegildo-zegna-silk-repp-tie',
      category: 'Ties & Pocket Squares',
      description: 'Hand-finished Italian silk tie in a classic repp stripe',
      images: [PH],
      price: 195.0,
      brand: 'Zegna',
      rating: 4.8,
      numReviews: 11,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Drakes Printed Silk Pocket Square',
      slug: 'drakes-printed-silk-pocket-square',
      category: 'Ties & Pocket Squares',
      description: 'Hand-rolled edges on a hand-printed silk pocket square',
      images: [PH],
      price: 85.0,
      brand: 'Drakes',
      rating: 4.6,
      numReviews: 8,
      stock: 15,
      isFeatured: false,
      banner: null,
    },

    // ─────────────────────────────────────────
    // FOOTWEAR
    // ─────────────────────────────────────────

    // Men's Shoes
    {
      name: 'Allen Edmonds Park Avenue Oxford',
      slug: 'allen-edmonds-park-avenue-oxford',
      category: "Men's Shoes",
      description: 'American-made cap-toe oxford in genuine calfskin',
      images: [PH],
      price: 395.0,
      brand: 'Allen Edmonds',
      rating: 4.9,
      numReviews: 23,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Cole Haan Grand Crosscourt Derby',
      slug: 'cole-haan-grand-crosscourt-derby',
      category: "Men's Shoes",
      description: 'Grand.ØS technology for all-day comfort in leather',
      images: [PH],
      price: 120.0,
      brand: 'Cole Haan',
      rating: 4.5,
      numReviews: 37,
      stock: 16,
      isFeatured: false,
      banner: null,
    },

    // Women's Shoes
    {
      name: 'Sam Edelman Hazel Kitten-Heel Mule',
      slug: 'sam-edelman-hazel-kitten-heel-mule',
      category: "Women's Shoes",
      description: 'Chic slip-on mule with a delicate kitten heel',
      images: [PH],
      price: 89.95,
      brand: 'Sam Edelman',
      rating: 4.4,
      numReviews: 46,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Steve Madden Irenee Strappy Heeled Sandal',
      slug: 'steve-madden-irenee-strappy-heeled-sandal',
      category: "Women's Shoes",
      description: 'Elegant multi-strap sandal with a block heel',
      images: [PH],
      price: 99.95,
      brand: 'Steve Madden',
      rating: 4.3,
      numReviews: 34,
      stock: 14,
      isFeatured: false,
      banner: null,
    },

    // Kids' Shoes
    {
      name: "New Balance Kids' 990v5 Sneaker",
      slug: 'new-balance-kids-990v5-sneaker',
      category: "Kids' Shoes",
      description: 'Heritage running silhouette scaled for little feet',
      images: [PH],
      price: 85.0,
      brand: 'New Balance',
      rating: 4.7,
      numReviews: 28,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Stride Rite Soft Motion Jazzy Mary Jane",
      slug: 'stride-rite-soft-motion-jazzy-mary-jane',
      category: "Kids' Shoes",
      description: 'Foot-shaped design supports healthy development',
      images: [PH],
      price: 55.0,
      brand: 'Stride Rite',
      rating: 4.5,
      numReviews: 19,
      stock: 18,
      isFeatured: false,
      banner: null,
    },

    // Sneakers & Athletic Shoes
    {
      name: 'Nike Air Force 1 Low',
      slug: 'nike-air-force-1-low',
      category: 'Sneakers & Athletic Shoes',
      description: 'The legend lives on — classic AF1 in clean white leather',
      images: [PH],
      price: 110.0,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 234,
      stock: 50,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Adidas Stan Smith Sneaker',
      slug: 'adidas-stan-smith-sneaker',
      category: 'Sneakers & Athletic Shoes',
      description: 'The iconic tennis shoe with three-stripe branding',
      images: [PH],
      price: 90.0,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 189,
      stock: 45,
      isFeatured: false,
      banner: null,
    },

    // Boots
    {
      name: 'Timberland 6-Inch Premium Waterproof Boot',
      slug: 'timberland-6-inch-premium-waterproof-boot',
      category: 'Boots',
      description: 'The original yellow boot — waterproof nubuck leather',
      images: [PH],
      price: 198.0,
      brand: 'Timberland',
      rating: 4.7,
      numReviews: 145,
      stock: 28,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'UGG Classic Short II Boot',
      slug: 'ugg-classic-short-ii-boot',
      category: 'Boots',
      description: 'Twin-face sheepskin lined in plush Twinface wool',
      images: [PH],
      price: 165.0,
      brand: 'UGG',
      rating: 4.8,
      numReviews: 312,
      stock: 22,
      isFeatured: false,
      banner: null,
    },

    // Sandals & Flip Flops
    {
      name: 'Birkenstock Arizona Sandal',
      slug: 'birkenstock-arizona-sandal',
      category: 'Sandals & Flip Flops',
      description: 'Contoured cork-latex footbed shaped to your feet',
      images: [PH],
      price: 110.0,
      brand: 'Birkenstock',
      rating: 4.8,
      numReviews: 278,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Havaianas Brasil Flip Flops",
      slug: 'havaianas-brasil-flip-flops',
      category: 'Sandals & Flip Flops',
      description: 'The original Brazilian rubber flip flop since 1962',
      images: [PH],
      price: 22.0,
      brand: 'Havaianas',
      rating: 4.5,
      numReviews: 196,
      stock: 80,
      isFeatured: false,
      banner: null,
    },

    // ─────────────────────────────────────────
    // OTHER / SPECIALTY
    // ─────────────────────────────────────────

    // Workwear & Uniforms
    {
      name: "Carhartt Men's Loose Fit Duck Bib Overall",
      slug: 'carhartt-loose-fit-duck-bib-overall',
      category: 'Workwear & Uniforms',
      description: 'Heavy-duty duck canvas built to take on any job site',
      images: [PH],
      price: 89.99,
      brand: 'Carhartt',
      rating: 4.7,
      numReviews: 91,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Dickies Women's Relaxed Straight Cargo Pant",
      slug: 'dickies-womens-relaxed-straight-cargo-pant',
      category: 'Workwear & Uniforms',
      description: 'Durable multi-pocket cargo pants for the job site',
      images: [PH],
      price: 39.99,
      brand: 'Dickies',
      rating: 4.4,
      numReviews: 47,
      stock: 30,
      isFeatured: false,
      banner: null,
    },

    // Loungewear
    {
      name: 'Skims Cotton Fleece Sweatpants',
      slug: 'skims-cotton-fleece-sweatpants',
      category: 'Loungewear',
      description: 'Ultra-soft fleece with a relaxed waistband for cozy days',
      images: [PH],
      price: 88.0,
      brand: 'Skims',
      rating: 4.6,
      numReviews: 63,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Barefoot Dreams CozyChic Lite Circle Cardigan',
      slug: 'barefoot-dreams-cozychic-lite-circle-cardigan',
      category: 'Loungewear',
      description: 'Cloud-like Lite knit wrap for ultimate weekend comfort',
      images: [PH],
      price: 116.0,
      brand: 'Barefoot Dreams',
      rating: 4.8,
      numReviews: 48,
      stock: 14,
      isFeatured: false,
      banner: null,
    },

    // Plus Size Clothing
    {
      name: 'Universal Standard Foundation Crewneck Tee',
      slug: 'universal-standard-foundation-crewneck-tee',
      category: 'Plus Size Clothing',
      description: 'Inclusive sizing from XS–4X in sustainable organic cotton',
      images: [PH],
      price: 50.0,
      brand: 'Universal Standard',
      rating: 4.7,
      numReviews: 57,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Eloquii Elements Faux Wrap Midi Dress',
      slug: 'eloquii-elements-faux-wrap-midi-dress',
      category: 'Plus Size Clothing',
      description: 'Flattering wrap silhouette in lightweight stretch fabric',
      images: [PH],
      price: 59.0,
      brand: 'Eloquii',
      rating: 4.5,
      numReviews: 34,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
